# Generated by Django 5.2.7 on 2025-10-18

import uuid
import django.contrib.auth.validators
from django.db import migrations, models


def populate_identifiers(apps, schema_editor):
    User = apps.get_model("core", "User")
    for user in User.objects.filter(identifier__isnull=True):
        user.identifier = uuid.uuid4()
        user.save(update_fields=["identifier"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="identifier",
            field=models.UUIDField(
                editable=False,
                null=True,
            ),
        ),
        migrations.RunPython(populate_identifiers, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                max_length=150,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                verbose_name="username",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="identifier",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                null=False,
                unique=True,
            ),
        ),
    ]
